version: 2.1
parameters:
  nix_path: 
    type: string
    default: "nixpkgs=channel:nixos-unstable"
orbs:
  nix: eld/nix@1.0.0
jobs:
  build:
    environment:
      NIX_PATH: nixpkgs=channel:nixpkgs-unstable
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - nix/install
      - run: "sudo /bin/sh -c 'wget https://github.com/benchkram/bob/releases/download/0.5.3/bob_0.5.3_linux_amd64 -O /usr/local/bin/bob && chmod +x /usr/local/bin/bob'"
      - run: bob build
workflows:
  build-project:
    jobs:
      - build